repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]  # Runs only on staged files
      - id: end-of-file-fixer
        stages: [commit]  # Runs only on staged files
