page_title="LVE Chatbot"
title="LVE ChatbotCustom ChatGPT"

# [openai]
# api_type="azure"
# api_version="2023-05-15"
# embeddings_model="embeddings-model" 
# chatgpt3_model="custom-chatgpt-model"
# chatgpt4_model="custom-chatgpt-model"

[openai]
api_type="None"
embeddings_model="text-embedding-ada-002"
chatgpt3_model="gpt-3.5-turbo-0613"
chatgpt4_model="gpt-3.5-turbo-0613"